(features)[Frontend] create details page
gbrl-pnhr/project-streaming-irede pull request #15
Opened 2024-07-23 19:09 UTC by PedroGeovani

2024-07-23 19:26 UTC, gbrl-pnhr requested changes

2024-07-23 19:26 UTC, gbrl-pnhr commented on src/App.vue
> +}
O componete já está global.

2024-07-23 19:26 UTC, gbrl-pnhr commented on src/components/FavoriteButton/button-favorite.vue
> +    startFavorite: Boolean,
Mudar o valor do startFavorite

2024-07-23 19:26 UTC, gbrl-pnhr commented on src/components/CardPoster/card-poster.vue
> +    name: "Card-Poster",
Padronizar o card poster: "CardPoster".

2024-07-23 19:26 UTC, gbrl-pnhr commented on src/views/details.vue
> +      favorite: false,
mudar o nome da variável para isFavorite (padrão booleano)

2024-07-23 19:26 UTC, gbrl-pnhr commented on src/views/details.vue
>      }
colocar as funções em um arquivo de util.

2024-07-24 17:12 UTC, milenaalcantara approved these changes

2024-07-24 17:18 UTC, gbrl-pnhr approved these changes

2024-07-24 17:18 UTC, merged