Feature/component pages
gbrl-pnhr/project-streaming-irede pull request #7
Opened 2024-07-15 17:06 UTC by gbrl-pnhr

Initially, the "structure-pages" component was created, which contains the base structure of the film poster display pages. Additionally, a card was created that shows the respective API posters.

2024-07-15 19:56 UTC, VictorManoel-Timbo approved these changes

2024-07-16 11:59 UTC, milenaalcantara commented on src/components/CardPoster/card-poster.vue
> +    props:{
Adicionar o espaço entre o : e a { => props: {

2024-07-16 13:01 UTC, milenaalcantara requested changes
Ótimo trabalho!

Precisamos de alguns ajustes que listei referente a identação e nomeação de atributos e métodos. Após os ajustes, aprovarei o PR.

2024-07-16 13:01 UTC, milenaalcantara commented on src/components/CardPoster/card-poster.vue
> +    props:{
Adicionar o espaço entre o : e a { => props: {

2024-07-16 13:01 UTC, milenaalcantara commented on src/components/CardPoster/card-poster.vue
> +            <img alt="user header" :src="`https://image.tmdb.org/t/p/w342/${url?.poster_path}`"/>
Aqui no alt, por que "**user** header"? Faz sentido? 
O alt é o texto alternativo, caso não haja imagem, tenta colocar algo que faça mais sentido com streams (ex: trocar user por stream ou poster, etc.)

2024-07-16 13:01 UTC, milenaalcantara commented on src/components/NavBar/nav-bar.vue
> +                    </Button>
identação

2024-07-16 13:01 UTC, milenaalcantara commented on src/views/home.vue
> +            all: new Array <StreamingService> (),
renomear a variável all para streamings

2024-07-16 13:01 UTC, milenaalcantara commented on src/views/home.vue
> +        getAll() {
renomear para getStreamings()

2024-07-16 13:01 UTC, milenaalcantara commented on src/views/home.vue
> +import { StreamingService } from '@/services/streaming.service';
O serviço da view fica na pasta view. Crie o serviço na view e caso o serviço não seja patilhado, coloque a view e seu respectivo serviço dentro de uma pasta exclusiva para a view.

2024-07-16 13:01 UTC, milenaalcantara commented on src/components/StructurePages/structure-pages.vue
> +        url: Array < StreamingService > ,
renomear a propriedade url

2024-07-16 16:52 UTC, milenaalcantara approved these changes

2024-07-16 16:56 UTC, merged